baseurl = "http://josepespasa.cat/"
languageCode = "en-us"
title = "Regression to the mean"
theme = "blackburn"
#author = "JosepER"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[indexes]
  tag = "tags"
  topic = "topics"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[author]
    name = "Josep Espasa Reig"
    email = "jespasareig@gmail.com"
    
  [params]
  # Shown in the home page
  subtitle = "My blog for data analysis and other things I learned the hard way."
  brand = "Blog"
  googleAnalytics = ""
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "12 Jan 2018, 15:04"
 
 [menu]
 
 [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
 
 [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"   
    
 [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    url = "mailto:jespasareig@gmail.com"
    
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"

[[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "https://twitter.com/Josepespasa"
  #facebook = "*"
 # instagram = "*"
  github = "JosepER/"
 # stackoverflow = "*"
  linkedin = "josepespasareig"