baseurl = "/"
languageCode = "en-us"
title = "Regression to the mean"
theme = "hugo-bootstrap-premium-master"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[author]
    name = "Josep Espasa Reig"
    email = "jespasareig@gmail.com"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/JosepER/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Josepespasa"

[params]
    description = "A website built through Hugo and blogdown."
    bootswatchtheme = "paper"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    showRightSidebar = true

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    github = "https://github.com/JosepER/"
    linkedin = "https://www.linkedin.com/in/josepespasareig/"
    twitter = "https://twitter.com/Josepespasa"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

